### ISSUE TITLE
Variable to disable mouse forwarding

### ISSUE THREAD

**Issue by Vitalflea** [unethicalite/unethicalite#108]
**Is your feature request related to a problem? Please describe.**

Whenever i am debugging and a breakpoint is hit, the global mouse hook stops too and causes the mouse to freeze for about 3 seconds (i think this is the problem)

**Describe the solution you'd like**

Add a task/arguement/env variable to disable the mouse forwarding stuff

**Comment by buracc** [comment]
env variable: disablenative=true
