### ISSUE TITLE
suggestion: Option to disable wilderness transports

### ISSUE THREAD

**Issue by Vitalflea** [unethicalite/unethicalite#117]
**Is your feature request related to a problem? Please describe.**
Explorer will sometimes unexpectedly use the edgeville switch to travel 

**Describe the solution you'd like**
A method to disable wilderness transports when source and destination are not in the wilderness

**Additional context**
It can be very dangerous

**Comment by alanbaumgartner** [comment]
Added in this commit https://github.com/unethicalite/unethicalite/commit/928c86dc1bdb5077520b9bf4f4b3ac7eb0dda172
