### ISSUE TITLE
bug: Mouse forwarding click location

### ISSUE THREAD

**Issue by Vitalflea** [unethicalite/unethicalite#127]
**Describe the bug**
setting a click location of any 2 numbers results in the mouse clicking 0,0

**To Reproduce**
use mouse forwarding and set a location, then click outside client

**Expected behavior**
clicks at the location specified

**Environment**
Windows 10 19041
unethicalite 1.0.2-SNAPSHOT
development branch
minimal & normal

**Additional context**
I dont think the config for the location is being set or its not being accessed correctly

**Comment by buracc** [comment]
it works fine for me, are you sure you typed it in correctly?

**Comment by Vitalflea** [comment]
![test39](https://user-images.githubusercontent.com/30124058/178809328-0a79df5d-2d5d-4767-bda4-4f90d7b09fbe.gif)

**Comment by buracc** [comment]
fixed
