### ISSUE TITLE
Failing to interact with Inventory items while off Inventory interface

### ISSUE THREAD

**Issue by Blogans** [unethicalite/unethicalite#146]
**Describe the bug**
Note: Very inconsistent
When trying to interact with an inventory item without the inventory being open, the client fails to interact regardless of interaction method. Inventory.contains code still executes as intended, but interacting doesn't. Not sure what the requirements are for this to happen, as there are periods of time where it interacts with items perfectly fine but that same code will not execute at a later time until you manually change interfaces which causes it to interact immediately. 

**To Reproduce**
1. Interact with inventory item using Inventory.getFirst() without the inventory interface open. 

**Expected behavior**
Interacts with the item from Inventory.getFirst() as intended.

**Screenshots**
Na

**Environment (please complete the following information):**
 - OS: Windows
 - Unethicalite version: 1.0.2
 - Launcher version: 1.0.1

**Additional context**
NA

**Comment by Blogans** [comment]
https://i.imgur.com/j03ZZRr.gif
Not very helpful, but should demonstrate whats happening. This was tested with 1.0.4

**Comment by buracc** [comment]
this should've been fixed, i don't remember what i exactly did, but i'll take a look

**Comment by buracc** [comment]
I've made it so that the inventory reloads whenever it changes, hopefully that'll fix it

**Comment by buracc** [comment]
reopen if issue reoccurs
