### ISSUE TITLE
Failing to interact with NPCs

### ISSUE THREAD

**Issue by Blogans** [unethicalite/unethicalite#147]
**Describe the bug**
During testing, Magic.cast failed to cast crumble undead on the Zombified Spawn at Vorkath. The code block was correctly firing, and the method to obtain the NPC varied between IDs and names. This was also very inconsistent, with it working as intended for large periods of time before breaking numerous times with no changes. 

**To Reproduce**
1. Use `Magic.cast(SpellBook.Standard.CRUMBLE_UNDEAD, NPCs.getNearest())` on an NPC, specifically in the case it was the Zombified spawn at Vorkath. 

**Expected behavior**
Would cast crumble undead on the NPC

**Screenshots**
https://i.imgur.com/gJa0Agd.png
Not a very helpful screenshot, but the task is shown to be correctly firing with no further interaction 

**Environment (please complete the following information):**
 - OS: Windows
 - Unethicalite version: 1.0.2
 - Launcher version: 1.0.1

**Additional context**
These are some menu logs printed when using mouse events. These still fired, without anything actually happening. 
```
2022-07-16 19:08:14:911 [Client] INFO  injected-client - |MenuAction|: MenuOption=Automated MenuTarget= Id=27592 Opcode=WIDGET_TARGET_ON_NPC/8 Param0=0 Param1=0 CanvasX=444 CanvasY=54
2022-07-16 19:08:14:911 [Client] INFO  injected-client - |MenuEntry|: Idx=0 MenuOption=Automated MenuTarget= Id=27592 MenuAction=WIDGET_TARGET_ON_NPC Param0=0 Param1=0 Consumer=null IsItemOp=false ItemOp=-1 ItemID=-1 Widget=null
```

**Comment by Blogans** [comment]
As per Ethan, I tested this using both Magic.cast and NPCPackets (with a click queue). Magic.cast failed to work consistently, whereas NPCPackets worked as intended. Something to note too is Magic.cast worked after manually clicking the spell once

**Comment by alanbaumgartner** [comment]
b921f9f7f3e1cc673619d46069e3ecdeb6b68713
fixed here
