### ISSUE TITLE
bug: bank withdraw-x action being consumed

### ISSUE THREAD

**Issue by Vitalflea** [unethicalite/unethicalite#148]
**Describe the bug**
sometimes the withdraw-x action gets consumed, looks like maybe its being input too fast

**To Reproduce**
use Withdraw-x

**Expected behavior**
items are withdrawn properly, for now i loop until i have withdrawn all items

**Environment**
Windows 10
1.0.3-SNAPSHOT

![test43](https://user-images.githubusercontent.com/30124058/179397157-b6d1994e-2253-4334-83ad-b0b684eea20f.gif)
(seeds are set to be withdrawn first and then logs)

**Comment by buracc** [comment]
should be fixed?
