### ISSUE TITLE
Multiple Plugin Dev Paths no longer working?

### ISSUE THREAD

**Issue by Joshua-Farin** [unethicalite/unethicalite#163]
On master branch I was using this method 1 or 2 nights ago, after updating it just defaults to the last path entered which in this case would be ...PATH=bar
```
PLUGIN_DEVELOPMENT_PATH=foo; PLUGIN_DEVELOPMENT_PATH=bar
```

**Comment by yuri-moens** [comment]
Are you sure this ever worked? Seems you're just overwriting the variable which would make it use only the last path. If you want multiple paths use a semicolon and don't forget to escape it, like this:

PLUGIN_DEVELOPMENT_PATH=foo\;bar\;baz

**Comment by buracc** [comment]
above comment has the correct notation

**Comment by Joshua-Farin** [comment]
Yeah you're right thanks again, idk i must've just typed it correctly the other night then did it wrong today. my b
