### ISSUE TITLE
bug: Explorer stuck on Veos Dialog

### ISSUE THREAD

**Issue by buracc** [unethicalite/unethicalite#168]
Bug submitted by: Wio#9069 (804531707956166718)

Stuck on dialog to travel to zeah if i havent been there before since there is no quick npc option to travel to port Piscarilius

**Comment by alanbaumgartner** [comment]
Unfortunately I don't have an account to test and fix this on and I'm not planning to make a new acc and bond it up anytime soon. Hopefully someone else can fix this or provide me a new members account but otherwise it'll probably stay like this.

**Comment by alanbaumgartner** [comment]
fixed
