### ISSUE TITLE
bug: Equipment interaction

### ISSUE THREAD

**Issue by buracc** [unethicalite/unethicalite#182]
Bug submitted by: .Tea#0001 (408346684796698635)

Interacting with equipped item will fail if the equipment tab has not been opened while the item is equipped, caching the options

**Comment by d-o-g** [comment]
You can re-construct equipment actions.

private static final int BASE_ACTION_PARAM = 451;
         private static final int MAX_CUSTOM_ACTIONS = 8;
         RSRS3CopiedNodeTable table = Functions.mapOrNull(this::getDefinition, RSItemDefinition::getProperties);
         if (table == null) {
         return new String[0];
         }
         List<String> actions = new ArrayList<>();
         actions.add("Remove");
         for (int param = BASE_ACTION_PARAM; param < (BASE_ACTION_PARAM + MAX_CUSTOM_ACTIONS) - 1; param++) {
         RSNode node = table.safeLookup(param);
         if (node instanceof RSObjectNode) {
         RSObjectNode obj = (RSObjectNode) node;
         if (obj.getValue() instanceof String) {
         actions.add(StringCommons.replaceColorTag((String) obj.getValue()));
         }
         }
         }
         actions.add("Examine");

**Comment by alanbaumgartner** [comment]
Should be fixed on dev
