### ISSUE TITLE
Exposing pathlenght

### ISSUE THREAD

**Issue by Manabarb** [unethicalite/unethicalite#186]
It would be nice to have access to either pathLength (Actor class) or getPathLength() ( used by ismoving() from the RSActorMixin) with the api.

**Comment by buracc** [comment]
What's the use case for this? It only returns 1 or 2 depending on whether ur running or not (as far as I know)

**Comment by Manabarb** [comment]
I was expecting it to give us the length of the path the entity had while moving since I wasn't really able to test it and was hoping to use it in order to get an indirect measure of distance to the target instead of doing it a second time with another method.
