### ISSUE TITLE
Walking to Entrana 

### ISSUE THREAD

**Issue by illumineawake** [unethicalite/unethicalite#200]
**Describe the bug**
Walking to Entrana currently does not work, tested using the latest version of Pathfinding on dev. Results are random, sometimes it heads to Taverley Dungeon, White Wolf Mountain or just fails to walk at all.

**To Reproduce**
Pathfind to Entrana from anywhere. A specific WorldPoint that should be reachable:
2848, 9745, 0 - this is in the cave underneath Entrana

DM for an account that has the requirements and is already setup to reach Entrana

**Environment (please complete the following information):**
- Latest commits on Dev branch

**Comment by alanbaumgartner** [comment]
Fixed on latest dev commit. ty for reporting
