### ISSUE TITLE
Walking - unable to enter Zanaris/shack - Source/Destination WP's appear backwards

### ISSUE THREAD

**Issue by illumineawake** [unethicalite/unethicalite#203]
**Describe the bug**
Latest pathfinding is unable to enter the shack that takes Player to Zanaris. It stops outside the shack and does not walk through door despite always providing WorldPoint's inside the shack.
Transport.json looks to have the Source and Destination WP's around the wrong way.

**To Reproduce**
Walk to WorldPoint inside shack such as: 3202 3169 0
Note above WorldPoint is the exact WorldPoint on opposite side of door, but same behaviour was encountered with any WP inside shack.

**Expected behavior**
Have Dramen staff equipped and open door with ID 2406. 

**Screenshots**
![image](https://user-images.githubusercontent.com/65434078/182288702-9ef4cbd2-ee00-4e8e-a47d-8b2896a64023.png)

**Environment (please complete the following information):**
 - 1.0.8-SNAPSHOT

**Comment by alanbaumgartner** [comment]
fixed in latest commit, check my dm for more context but you can directly call `Movement.walkTo(zanaris)` instead of to inside the shack
