### ISSUE TITLE
bug: Explorer leak maybe?

### ISSUE THREAD

**Issue by buracc** [unethicalite/unethicalite#205]
Bug submitted by: Wio#9069 (804531707956166718)

https://gyazo.com/b0cea03d32992394bde637dbdf6bc5f5 Explorer idles and caues lag when trying to reach 2653,9767,0  but works prefectly anywhere else like GE https://gyazo.com/6792047342cfa111e9196c1228aef5bf

**Comment by alanbaumgartner** [comment]
Not a memory leak, Since the destination isn't walkable (the web that needs to be slashed is blocking it), the pathfinder explores tiles until it hits the max visited tile count. Try using `2653,9765,0`
