### ISSUE TITLE
bug: Explorer leak

### ISSUE THREAD

**Issue by buracc** [unethicalite/unethicalite#212]
Bug submitted by: Wio#9069 (804531707956166718)

Same issue persists with 2653,9765,0 please see https://gyazo.com/f439f5c440f70ba7b7006f30d845c973 https://gyazo.com/d32aa3e96f9451d9fbfc5aa35d5b378a https://gyazo.com/6634446ace76ef4234a8764e337a9e9b

**Comment by alanbaumgartner** [comment]
You dont have a lightsource, the destination is not reachable.
