### ISSUE TITLE
bug: boat transport from port sarim to karmja has problems

### ISSUE THREAD

**Issue by Vitalflea** [unethicalite/unethicalite#217]
**Describe the bug**
trying to use Movement.walkTo to go to karmja from port sarim results in trying to walk across the water instead of using the boat

**To Reproduce**
use Movement.walkTo to karmja from port sarim

**Expected behavior**
uses 30 coins to board the boat

**Environment**
Mac, dev branch

**Comment by Vitalflea** [comment]
path overlay: <img width="265" alt="Screen Shot 2022-08-04 at 3 52 18 PM" src="https://user-images.githubusercontent.com/30124058/182968709-86a67713-1049-4ecc-ae57-10633044e7fe.png">

**Comment by alanbaumgartner** [comment]
added
