### ISSUE TITLE
Web Walker fails to handle door to get into Waterfall Quest Treasure Room (quest finale)

### ISSUE THREAD

**Issue by illumineawake** [unethicalite/unethicalite#227]
**Describe the bug**
![image](https://user-images.githubusercontent.com/65434078/184804910-6f3faba2-cd52-4218-a445-8de0c2295529.png)

**To Reproduce**
1. Attempt to travel to last room for Waterfall Quest using Web Walker

**Expected behavior**
Open door

**Comment by Hoodz** [comment]
dont you need to use a key to open that door? @illumineawake

**Comment by illumineawake** [comment]
@Hoodz Just suss'd it out and you're right. My web-walker handled that door previously but if there's an item requirement then it should be handled manually or added as a item requirement transport. Closing for now.
