### ISSUE TITLE
Mouse forwarding client region

### ISSUE THREAD

**Issue by Vitalflea** [unethicalite/unethicalite#89]
**Describe the bug**
While the client is not the foreground window and the mouse is in the region of the client, mouse forwarding will not work

**To Reproduce**
1. Enable mouse forwarding
2. Move another window over the client 
3. click on the non-client window while mouse is in the client region

**Expected behavior**
Mouse forwarding works

**Screenshots**
https://imgur.com/a/XL3gdRg

**Environment (please complete the following information):**
 - OS: Windows 10

**Comment by buracc** [comment]
Semi-intended because I haven't been able to come up with a solution to figure out whether the click was inside the client frame or not.

**Comment by buracc** [comment]
Fixed
